### ISSUE TITLE
Define necessary Composer extras for WordPress core

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/wordpress-composer#1]
```
        "type": "wordpress-core",
        "require": {
          "johnpbloch/wordpress-core-installer": "~0.1"
        },
        "extra": {
          "wordpress-install-dir": "web/wp"
        }
```

**Comment by ataylorme** [comment]
We will need these updates to `composer.json` to facilitate installing WordPress in a subdirectory

**Comment by stevector** [comment]
And we'll need to add `replace`, yes? https://getcomposer.org/doc/04-schema.md#replace

**Comment by ataylorme** [comment]
+1 to adding replace

**Comment by ataylorme** [comment]
> Lists packages that are replaced by this package.

@stevector actually since WordPress core doesn't have a `composer.json` there is no package to replace. I should use replace in my WordHat fork though.
