### ISSUE TITLE
`4.x-dev` still aliased to `dev-master` even for WordPress 5.x

### ISSUE THREAD

**Issue by dero** [pantheon-systems/wordpress-composer#1]
The `composer.json` still [aliases `4.x` versions to `dev-master`](https://github.com/pantheon-systems/wordpress-composer/blob/755c1ec78e5b255e87dfa1683f8e71d3cec03aa3/composer.json#L7) even after recent update to WordPress 5.0. This introduces breaking changes. E.g. our `composer.json` requires this package as:

```
"minimum-stability": "dev",
...
"require": {
  "pantheon-systems/wordpress-composer": "^4.9"
}
```

The aforementioned alias then resolves `^4.9` to `dev-master`, which currently contains WordPress 5.0.0. This is unexpected and a breaking change.

**Comment by greg-1-anderson** [comment]
Thanks for reporting this. 

Updated dev-master to 5.x in https://github.com/pantheon-systems/wordpress-composer/commit/ccf757e6d176758eb347e0c246106739c6c85923. I also created a 4.x branch that Packagist will find when searching for dev versions of ^4.x.

Seems to work now.
