### ISSUE TITLE
Is this a working example?

### ISSUE THREAD

**Issue by slavafomin** [pantheon-systems/wordpress-composer#2]
Hey! Is this a working example?

Why WordPress core files are committed to the repository?

**Comment by greg-1-anderson** [comment]
This repository is a clone of WordPress core with the addition of a composer.json file. It is intended to be included from a Composer-managed project, for WordPress sites hosted on the Pantheon platform.

For a working example, see [example-wordpress-composer](https://github.com/pantheon-systems/example-wordpress-composer).

**Comment by slavafomin** [comment]
Okay, thanks. I was strangely directed here by the support agent at Pantheon.
