### ISSUE TITLE
Security backports for older branches are missing

### ISSUE THREAD

**Issue by schlessera** [pantheon-systems/wordpress-composer#26]
While trying to pull in version `5.7.6` for a project, I noticed that this repo does not include all the security backports for older versions. As an example, the `5.7` branch only has releases up to `5.7.2`.

Is this something that can be changed so that the repository includes the latest security backports for all older branches as well?

**Comment by greg-1-anderson** [comment]
Yes, we could provide this. This project is created and maintained via automation. It is probably stopping as soon as it finds a version that already exists, rather than looking for any missing version. We'll look into it.

**Comment by greg-1-anderson** [comment]
Created [CMS-826](https://getpantheon.atlassian.net/browse/CMS-826) for internal tracking.

**Comment by schlessera** [comment]
It looks like this was resolved.

**Comment by jazzsequence** [comment]
Confirmed resolved.
