### ISSUE TITLE
Pantheon_Cache error on latest version

### ISSUE THREAD

**Issue by jamesonnuss** [pantheon-systems/wordpress-composer#28]
Fatal error: Cannot redeclare Pantheon_Cache() (previously declared in /app/web/wp-content/mu-plugins/pantheon-mu-plugin/inc/pantheon-page-cache.php:513) in /app/web/wp-content/mu-plugins/pantheon/pantheon-page-cache.php on line 546

**Comment by jspellman814** [comment]
This is the same issue as a previous report, #27. We are tracking internally as BUGS-5622.
