### ISSUE TITLE
WordPress Composer Installer Outdated

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/wordpress-composer#3]
[`johnpbloch/wordpress-core-installer`](https://github.com/johnpbloch/wordpress-core-installer) had a `1.0` release. We should require version `^1.0`.

**Comment by ataylorme** [comment]
I'm getting an odd error with `pantheon-systems/wordpress-composer`

```
[InvalidArgumentException]
  Two packages (pantheon-systems/wordpress-composer and johnpbloch/wordpress-core) cannot share the same directory!
```

**Comment by ataylorme** [comment]
Turns out when `wordpress-composer` is installed as a dependency it already declares `"wordpress-install-dir": "web/wp"` in `extra` and declaring it again causes this issue. We should probably remove the declaration from `example-wordpress-composer`

**Comment by ataylorme** [comment]
I traced my issue to [Google Site Kit](https://github.com/google/site-kit-wp/issues/38) requiring a copy of WordPress core.

However, we should still update to the `1.x` stable version of `johnpbloch/wordpress-core-installer`

**Comment by tedw** [comment]
The latest version is now 2.0 https://github.com/johnpbloch/wordpress-core-installer/releases

https://github.com/pantheon-systems/wordpress-composer/blob/351582e0e476e116e6560cf73f8b64d1a975afc5/composer.json#L12

The old version triggers this warning when using Composer 2:

>Loading "johnpbloch/wordpress-core-installer" which is a legacy composer-installer built for Composer 1.x, it is likely to cause issues as you are running Composer 2.x.

**Comment by tedw** [comment]
@greg-1-anderson Sorry to bug you but would really appreciate it if you could bump the version of `johnpbloch/wordpress-core-installer` so it’s compatible with Composer 2 (see above). Thanks!

FYI in case anyone else comes across this, I’m using the following code to override the old version for the time being:
```json
"johnpbloch/wordpress-core-installer": "2.0.0 as 0.1.2",
```

**Comment by greg-1-anderson** [comment]
We have this in our backlog, but haven't pulled it into a sprint yet.

**Comment by tedw** [comment]
What do folks think about replacing `johnpbloch/wordpress-core-installer` with `roots/wordpress`? Seems to be better maintained. See https://roots.io/updates-to-roots-wordpress-composer-package/ for details.

**Comment by jazzsequence** [comment]
updated in https://github.com/pantheon-systems/wordpress-composer/commit/316cf20a6bae4cee275927510922aede0051222c
